/**
 * PostgreSQL connection for tachyon-workers
 *
 * Provides a single shared Kysely<DB> instance used by all worker processors
 * that need to read from or write to the Tachyon PostgreSQL database.
 *
 * Why Kysely?
 * Kysely is a type-safe SQL query builder (ORM). The `DB` type (generated by
 * kysely-codegen from the live schema) gives every query full TypeScript
 * coverage — column names, filter values, and return shapes are all checked
 * at compile time.
 *
 * Why a shared pool here?
 * Worker processors run concurrently (controlled by BULLMQ_CONCURRENCY).
 * A pg.Pool holds a fixed set of reusable connections and hands them out
 * to concurrent callers, then reclaims them when done. This is far more
 * efficient than opening a new connection per job.
 *
 * Connection limits:
 * - max: 50  — upper bound on open connections from this process
 * - idleTimeoutMillis: 30s  — a connection idle longer than this is closed
 * - connectionTimeoutMillis: 5s — if no connection is available within 5s, fail fast
 *
 * SSL:
 * POSTGRES_SSL=true enables SSL with self-signed cert support
 * (rejectUnauthorized: false). Required for DigitalOcean managed PostgreSQL.
 * Local dev leaves SSL disabled.
 *
 * Note: Workers should NOT import the Kysely instance from tachyon-db directly
 * — that package exports its own pool tuned for the API server. Workers manage
 * their own pool so concurrency limits can be tuned independently.
 */

import { Kysely, PostgresDialect } from "kysely";
import { Pool } from "pg";
import type { DB } from "@tachyonapp/tachyon-db";

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  max: 50,
  idleTimeoutMillis: 30_000,
  connectionTimeoutMillis: 5_000,
  ssl:
    process.env.POSTGRES_SSL === "true" ? { rejectUnauthorized: false } : false,
});

export const db = new Kysely<DB>({
  dialect: new PostgresDialect({ pool }),
});
